config/routes.rb
Intern::Application.routes.draw do
  resources :saved_student_profiles

  resources :saved_job_postings

  ActiveAdmin.routes(self)

  devise_for :users, :controllers => {:registrations => "registrations"}

  root :to => "student_profiles#index"

  resources :skills
  resources :stu_references
  resources :job_postings do
    collection do
      get 'search'
    end
  end
  resources :company_profiles
  resources :student_profiles do
  	  collection do
			get 'search'
	end
  end
  resources :stu_work_experiences

  resources :qsorts do
    post :sort, on: :collection
  end

  match "about" => "about#index"

end

app/models/saved_student_profile.rb
class SavedStudentProfile < ActiveRecord::Base
  attr_accessible :company_profile_id, :culture, :school_text, :skill_text, :year_text

  belongs_to :company_profile
end

app/controllers/saved_student_profiles_controller.rb
class SavedStudentProfilesController < ApplicationController
  before_filter :authenticate_user!
  #keep user from accessing their profile if they haven't created it yet
  before_filter :profile_redir
  # #redirect company if they haven't been verified
  # before_filter :verified?
  #keep user from accessing any method that isn't connected to their profile
  before_filter {
      |c|
    if SavedStudentProfile.exists?(params[:id])
      c.deny_access(SavedStudentProfile.find(params[:id]).company_profile_id)
    else
      if c.get_profile_type != "company"
        c.deny_access(-1)
      end
    end}

  # GET /saved_student_profiles/1/edit
  def edit
    @saved_student_profile = SavedStudentProfile.find(params[:id])
    @cultures = ['']
    Groups.all.each do |culture|
      @cultures.push(culture.description)
    end
  end

  # PUT /saved_student_profiles/1
  # PUT /saved_student_profiles/1.json
  def update
    @saved_student_profile = SavedStudentProfile.find(params[:id])

    respond_to do |format|
      if @saved_student_profile.update_attributes(params[:saved_student_profile])
        format.html { redirect_to search_student_profiles_url, notice: 'Saved search was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @saved_student_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /saved_student_profiles/1
  # DELETE /saved_student_profiles/1.json
  def destroy
    @saved_student_profile = SavedStudentProfile.find(params[:id])
    @saved_student_profile.destroy

    respond_to do |format|
      format.html { redirect_to search_student_profiles_url, :notice => 'Saved search was successfully destroyed'}
      format.json { head :no_content }
    end
  end
end

app/helpers/saved_student_profiles_helper.rb
module SavedStudentProfilesHelper
end

app/views/saved_student_profiles/_form.html.erb
<%= form_for(@saved_student_profile) do |f| %>
  <% if @saved_student_profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@saved_student_profile.errors.count, "error") %> prohibited this saved_student_profile from being saved:</h2>

      <ul>
      <% @saved_student_profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <p>
      <%= f.label :school %><br/>
      <%= f.text_field :school_text %>
    </p>
    <p>
      <%= f.label :year %><br/>
      <%= f.select :year_text, [['', ''], ['Freshman', 'Freshman'], ['Sophomore', 'Sophomore'], ['Junior', 'Junior'], ['Senior', 'Senior']] %>
    </p>
    <p>
      <%= f.label :skill %><br/>
      <%= f.text_field :skill_text %>
    </p>
    <p>
      <%= f.label :culture %><br/>
      <%= f.select :culture, options_for_select(@cultures) %>
    </p>

  <div class="actions">
    <%= f.submit "Update Saved Search" %>
  </div>
<% end %>

app/views/saved_student_profiles/edit.html.erb
<h1>Editing Saved Search</h1>

<%= render 'form' %>

<%= link_to 'Cancel', search_student_profiles_url %>

app/views/saved_student_profiles/index.html.erb
<h1>Listing saved_student_profiles</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @saved_student_profiles.each do |saved_student_profile| %>
  <tr>
    <td><%= link_to 'Show', saved_student_profile %></td>
    <td><%= link_to 'Edit', edit_saved_student_profile_url(saved_student_profile) %></td>
    <td><%= link_to 'Destroy', saved_student_profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Saved student profile', new_saved_student_profile_url %>

app/views/saved_student_profiles/new.html.erb
<h1>New saved_student_profile</h1>

<%= render 'form' %>

<%= link_to 'Back', saved_student_profiles_url %>

app/views/saved_student_profiles/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_saved_student_profile_url(@saved_student_profile) %> |
<%= link_to 'Back', saved_student_profiles_url %>