config/routes.rb
Intern::Application.routes.draw do
  resources :saved_student_profiles

  resources :saved_job_postings

  ActiveAdmin.routes(self)

  devise_for :users, :controllers => {:registrations => "registrations"}

  root :to => "student_profiles#index"

  resources :skills
  resources :stu_references
  resources :job_postings do
    collection do
      get 'search'
    end
  end
  resources :company_profiles
  resources :student_profiles do
  	  collection do
			get 'search'
	end
  end
  resources :stu_work_experiences

  resources :qsorts do
    post :sort, on: :collection
  end

  match "about" => "about#index"

end

app/models/saved_job_posting.rb
class SavedJobPosting < ActiveRecord::Base
  attr_accessible :culture, :description_text, :paid_text, :position_text, :requirements_text, :student_profile_id

  belongs_to :student_profile
end

app/controllers/saved_job_postings_controller.rb
class SavedJobPostingsController < ApplicationController
  before_filter :authenticate_user!
  #keep user from accessing their profile if they haven't created it yet
  before_filter :profile_redir
  #redirect company if they haven't been verified
  before_filter :verified?
  #keep user from accessing any method that isn't connected to their profile
  before_filter {
      |c|
    if SavedJobPosting.exists?(params[:id])
      c.deny_access(SavedJobPosting.find(params[:id]).student_profile_id)
    else
      if c.get_profile_type != "student"
        c.deny_access(-1)
      end
    end}

  # GET /saved_job_postings/1/edit
  def edit
    @saved_job_posting = SavedJobPosting.find(params[:id])
    @cultures = ['']
    Groups.all.each do |culture|
      @cultures.push(culture.description)
    end
    #@pay = ['', 'Paid', 'Unpaid']
  end

  # PUT /saved_job_postings/1
  # PUT /saved_job_postings/1.json
  def update
    @saved_job_posting = SavedJobPosting.find(params[:id])

    respond_to do |format|
      if @saved_job_posting.update_attributes(params[:saved_job_posting])
        format.html { redirect_to search_job_postings_url, notice: 'Saved search was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @saved_job_posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /saved_job_postings/1
  # DELETE /saved_job_postings/1.json
  def destroy
    @saved_job_posting = SavedJobPosting.find(params[:id])
    @saved_job_posting.destroy

    respond_to do |format|
      format.html { redirect_to search_job_postings_url, :notice => 'Saved search was successfully destroyed' }
      format.json { head :no_content }
    end
  end
end

app/helpers/saved_job_postings_helper.rb
module SavedJobPostingsHelper
end

app/views/saved_job_postings/_form.html.erb
<%= form_for(@saved_job_posting) do |f| %>
  <% if @saved_job_posting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@saved_job_posting.errors.count, "error") %> prohibited this saved_job_posting from being saved:</h2>

      <ul>
      <% @saved_job_posting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <p>
      <%= f.label :position %><br/>
      <%= f.text_field :position_text%>
    </p>
    <p>
      <%= f.label :description %><br/>
      <%= f.text_field :description_text %>
<%# text_field_tag :year_text %>
    </p>
    <p>
      <%= f.label :paid %><br/>
      <%= f.select :paid_text, [['', ''], ['Paid', 'Paid'], ['Unpaid', 'Unpaid']] %>
    </p>
    <p>
      <%= f.label :culture %><br/>
      <%= f.select :culture, options_for_select(@cultures) %>
    </p>

  <div class="actions">
    <%= f.submit "Update Saved Search" %>
  </div>
<% end %>

app/views/saved_job_postings/edit.html.erb
<h1>Editing Saved Search</h1>

<%= render 'form' %>

<%= link_to 'Cancel', search_job_postings_url %>

app/views/saved_job_postings/index.html.erb
<h1>Listing saved_job_postings</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @saved_job_postings.each do |saved_job_posting| %>
  <tr>
    <td><%= link_to 'Show', saved_job_posting %></td>
    <td><%= link_to 'Edit', edit_saved_job_posting_url(saved_job_posting) %></td>
    <td><%= link_to 'Destroy', saved_job_posting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Saved job posting', new_saved_job_posting_url %>

app/views/saved_job_postings/new.html.erb
<h1>New saved_job_posting</h1>

<%= render 'form' %>

<%= link_to 'Back', saved_job_postings_url %>

app/views/saved_job_postings/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_saved_job_posting_url(@saved_job_posting) %> |
<%= link_to 'Back', saved_job_postings_url %>