config/routes.rb
Intern::Application.routes.draw do
  resources :saved_student_profiles

  resources :saved_job_postings

  ActiveAdmin.routes(self)

  devise_for :users, :controllers => {:registrations => "registrations"}

  root :to => "student_profiles#index"

  resources :skills
  resources :stu_references
  resources :job_postings do
    collection do
      get 'search'
    end
  end
  resources :company_profiles
  resources :student_profiles do
  	  collection do
			get 'search'
	end
  end
  resources :stu_work_experiences

  resources :qsorts do
    post :sort, on: :collection
  end

  match "about" => "about#index"

end

app/models/job_posting.rb
class JobPosting < ActiveRecord::Base
  #SET ACCESSIBLE ATTRIBUTES HERE
  attr_accessible :company_profile_id, :job_description, :job_end, :job_id, :job_paid, :job_requirements, :job_start, :position, :position_time, :posted_on, :user_id

  #ASSOCIATIONS HERE
  belongs_to :company_profile

  #VALIDATIONS HERE
=begin
=end

  validate :validate_end_date_before_start_date
  def validate_end_date_before_start_date
      errors.add(:job_end, "must be greater than Start Date.") if job_end < job_start
  end

  validates :position_time, :job_paid, :position,
            :length => { :minimum => 1,
                         :message => "This field cannot be empty" }
  validates :job_description, :job_requirements,
            :length => { :maximum => 300,
                         :message => "Over 300 characters" }

end

app/controllers/job_postings_controller.rb
class JobPostingsController < InheritedResources::Base
# GET /job_postings
# GET /job_postings.json
  before_filter :authenticate_user!, :get_user
  #keep user from accessing their profile if they haven't created it yet
  before_filter :profile_redir
  #keep user from accessing any method that isn't connected to their profile
  before_filter(:except =>[:index, :search]) {
      |c|
    if JobPosting.exists?(params[:id])
      c.deny_access(JobPosting.find(params[:id].to_i).company_profile_id)
    else
      if c.get_profile_type != "company"
        c.deny_access(-1)
      end
    end}
  #redirect company if they haven't been verified
  # before_filter :verified?


  def index
    @job_postings = JobPosting.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @job_postings }
    end
  end

  def search()

    @job_postings_all = JobPosting.all
    @saved = SavedJobPosting.find_all_by_student_profile_id(@user.id)
    @return = []
    @cultures = ['']
    Groups.all.each do |culture|
      @cultures.push(culture.description)
    end
    @pay = ['', 'Paid', 'Unpaid']

    #@params = params[:student_profile_id] = @user.id
    if params[:save_search]
      #@saved_job_posting = SavedJobPosting.new(params[:saved_job_posting])
      @saved_job_posting = SavedJobPosting.new
      #@saved_job_posting.student_profile_id = params[:student_profile_id]
      @saved_job_posting.student_profile_id = @user.id
      @saved_job_posting.position_text = params[:position_text]
      @saved_job_posting.description_text = params[:description_text]
      @saved_job_posting.paid_text = params[:paid_text]
      @saved_job_posting.requirements_text = params[:requirements_text]
      @saved_job_posting.culture = params[:culture]

      respond_to do |format|
        if @saved_job_posting.save
          format.html { redirect_to :back, notice: 'Saved job posting was successfully created.' }
          format.json { render json: @saved_job_posting, status: :created, location: @saved_job_posting }
        else
          format.html { render action: "new" }
          format.json { render json: @saved_job_posting.errors, status: :unprocessable_entity }
        end
      end
    end

    if params[:position_text]
      if params[:position_text] != "" and params[:description_text] != "" and params[:paid_text] != "" and params[:requirements_text] != ""
        match_term1 = "%" + params[:position_text] + "%"
        match_term2 = "%" + params[:description_text] + "%"
        match_term3 = params[:paid_text]
        match_term4 = "%" + params[:requirements_text] + "%"
        @job_postings = JobPosting.where("Position LIKE ? AND Job_description LIKE ? AND Job_paid = ? AND Job_requirements LIKE ?", match_term1, match_term2, match_term3, match_term4)
      elsif params[:position_text] != "" and params[:description_text] != "" and params[:paid_text] != ""
        match_term1 = "%" + params[:position_text] + "%"
        match_term2 = "%" + params[:description_text] + "%"
        match_term3 = params[:paid_text]
        @job_postings = JobPosting.where("Position LIKE ? AND Job_description LIKE ? AND Job_paid = ?", match_term1, match_term2, match_term3)
      elsif params[:position_text] != "" and params[:description_text] != "" and params[:requirements_text] != ""
        match_term1 = "%" + params[:position_text] + "%"
        match_term2 = "%" + params[:description_text] + "%"
        match_term4 = "%" + params[:requirements_text] + "%"
        @job_postings = JobPosting.where("Position LIKE ? AND Job_description LIKE ? AND Job_requirements LIKE ?", match_term1, match_term2, match_term4)
      elsif params[:position_text] != "" and params[:paid_text] != "" and params[:requirements_text] != ""
        match_term1 = "%" + params[:position_text] + "%"
        match_term3 = params[:paid_text]
        match_term4 = "%" + params[:requirements_text] + "%"
        @job_postings = JobPosting.where("Position LIKE ? AND Job_paid = ? AND Job_requirements LIKE ?", match_term1, match_term3, match_term4)
      elsif params[:description_text] != "" and params[:paid_text] != "" and params[:requirements_text] != ""
        match_term2 = "%" + params[:description_text] + "%"
        match_term3 = params[:paid_text]
        match_term4 = "%" + params[:requirements_text] + "%"
        @job_postings = JobPosting.where("Job_description LIKE ? AND Job_paid LIKE ? AND Job_requirements LIKE ?", match_term2, match_term3, match_term4)
      elsif params[:position_text] != "" and params[:description_text] != ""
        match_term1 = "%" + params[:position_text] + "%"
        match_term2 = "%" + params[:description_text] + "%"
        @job_postings = JobPosting.where("Position LIKE ? AND Job_description LIKE ?", match_term1, match_term2)
      elsif params[:position_text] != "" and params[:paid_text] != ""
        match_term1 = "%" + params[:position_text] + "%"
        match_term3 = params[:paid_text]
        @job_postings = JobPosting.where("Position LIKE ? AND Job_paid = ?", match_term1, match_term3)
      elsif params[:position_text] != "" and params[:requirements_text] != ""
        match_term1 = "%" + params[:position_text] + "%"
        match_term4 = "%" + params[:requirements_text] + "%"
        @job_postings = JobPosting.where("Position LIKE ? AND Job_requirements LIKE ?", match_term1, match_term4)
      elsif params[:description_text] != "" and params[:paid_text] != ""
        match_term2 = "%" + params[:description_text] + "%"
        match_term3 = params[:paid_text]
        @job_postings = JobPosting.where("Job_description LIKE ? AND Job_paid = ?", match_term2, match_term3)
      elsif params[:description_text] != "" and params[:requirements_text] != ""
        match_term2 = "%" + params[:description_text] + "%"
        match_term4 = "%" + params[:requirements_text] + "%"
        @job_postings = JobPosting.where("Job_description LIKE ? AND Job_requirements LIKE ?", match_term2, match_term4)
      elsif params[:paid_text] != "" and params[:requirements_text] != ""
        match_term3 = params[:paid_text]
        match_term4 = "%" + params[:requirements_text] + "%"
        @job_postings = JobPosting.where("Job_paid = ? AND Job_requirements LIKE ?", match_term3, match_term4)
      elsif params[:position_text] != ""
        match_term1 = "%" + params[:position_text] + "%"
        @job_postings = JobPosting.where("Position LIKE ?", match_term1)
      elsif params[:description_text] != ""
        match_term2 = "%" + params[:description_text] + "%"
        @job_postings = JobPosting.where("Job_description LIKE ?", match_term2)
      elsif params[:paid_text] != ""
        match_term3 = params[:paid_text]
        @job_postings = JobPosting.where("Job_paid = ?", match_term3)
      elsif params[:requirements_text] != ""
        match_term4 = "%" + params[:requirements_text] + "%"
        @job_postings = JobPosting.where("Job_requirements LIKE ?", match_term4)
      end

      if params[:culture] != ''
        #culture is set but there are no search hits
        if @job_postings.nil?
          @job_postings_all.each do |profile|
            if CompanyProfile.find(profile.company_profile_id).qsort == params[:culture]
              @return.append(profile)
            end
          end
          #culture is set and there are search hits
        else
          @job_postings.each do |profile|
            if CompanyProfile.find(profile.company_profile_id).qsort == params[:culture]
              @return.append(profile)
            end
          end
        end
        #no culture is set
      else
        @return = @job_postings
      end
    else
      #when the search page is initially visited, displays all of the job postings
      #@return = @job_postings_all
    end
    @position_text = params[:position_text]
    @description_text = params[:description_text]
    @paid_text = params[:paid_text]
    @requirements_text = params[:requirements_text]
    @culture = params[:culture]
  end


  # GET /job_postings/1
  # GET /job_postings/1.json
  def show
    @job_posting = JobPosting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job_posting }
    end
  end

  # GET /job_postings/new
  # GET /job_postings/new.json
  def new
    @job_posting = JobPosting.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job_posting }
    end
  end

  # GET /job_postings/1/edit
  def edit
    @job_posting = JobPosting.find(params[:id])
  end

  # POST /job_postings
  # POST /job_postings.json
  def create
    @job_posting = JobPosting.new(params[:job_posting])
    @job_posting.user_id = @user.id
    @job_posting.company_profile_id = @user.id
    @job_posting.posted_on = Time.now

    respond_to do |format|
      if @job_posting.save
        format.html { redirect_to company_profile_url(@user), notice: 'Job posting was successfully created.' }
        format.json { render json: @job_posting, status: :created, location: @job_posting }
      else
        format.html { render action: "new" }
        format.json { render json: @job_posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /job_postings/1
  # PUT /job_postings/1.json
  def update
    @job_posting = JobPosting.find(params[:id])

    respond_to do |format|
      if @job_posting.update_attributes(params[:job_posting])
        format.html { redirect_to company_profile_url(@user), notice: 'Job posting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @job_posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_postings/1
  # DELETE /job_postings/1.json
  def destroy
    @job_posting = JobPosting.find(params[:id])
    @job_posting.destroy

    respond_to do |format|

app/helpers/job_postings_helper.rb
module JobPostingsHelper
end

app/views/job_postings/_form.html.erb
<%= form_for(@job_posting) do |f| %>
  <% if @job_posting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job_posting.errors.count, "error") %> prohibited this job_posting from being saved:</h2>

      <ul>
      <% @job_posting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :position %><br />
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :job_description %><br />
    <%= f.text_area :job_description %>
  </div>
  <div class="field">
    <%= f.label :job_start %><br />
    <%= f.date_select :job_start %>
  </div>
  <div class="field">
    <%= f.label :job_end %><br />
    <%= f.date_select :job_end %>
  </div>

  <div class="field">
    <%= f.label :position_time %><br />
    <%= f.select :position_time, [['Full-time', 'Full-time'], ['Part-time', 'Part-time']] %>
  </div>
  <div class="field">
    <%= f.label :job_paid %><br />
    <%= f.select :job_paid, [['Paid', 'Paid'], ['Unpaid', 'Unpaid']] %>
  </div>
  <div class="field">
    <%= f.label :job_requirements %><br />
    <%= f.text_area :job_requirements %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/job_postings/edit.html.erb
<h1>Editing Job Posting</h1>

<%= render 'form' %>

<%= link_to 'Cancel', company_profile_url(@user) %>

app/views/job_postings/index.html.erb
<h1>Listing Job Postings</h1>

<table>
  <tr>
    <th>Company Profile</th>
    <th>Company Culture Grouping</th>
    <th>Position</th>
    <th>Job description</th>
    <th>Job start</th>
    <th>Job end</th>
    <th>Posted on</th>
    <th>Position time</th>
    <th>Job paid</th>
    <th>Job requirements</th>

  </tr>

  <% @job_postings.each do |job_posting| %>
      <tr>
        <% com_prof = CompanyProfile.find(job_posting.company_profile_id) %>
        <td><%= link_to com_prof.company_name, company_profile_url(com_prof) %></td>
        <td><%= com_prof.qsort %></td>
        <td><%= job_posting.position %></td>
        <td><%= job_posting.job_description %></td>
        <td><%= job_posting.job_start %></td>
        <td><%= job_posting.job_end %></td>
        <td><%= job_posting.posted_on %></td>
        <td><%= job_posting.position_time %></td>
        <td><%= job_posting.job_paid %></td>
        <td><%= job_posting.job_requirements %></td>

      </tr>
  <% end %>
</table>


<br />

app/views/job_postings/new.html.erb
<h1>New Job Posting</h1>

<%= render 'form' %>

<%= link_to 'Cancel', company_profile_url(@user) %>

app/views/job_postings/search.html.erb
<p id="notice"><%= notice %></p>

<div style="overflow: auto">

  <div style="display:inline-block; float:left; width:20%;">
    <h3>Search Job Postings</h3>

    <%= form_tag search_job_postings_url, :method => 'get' do %>
        <p>
          <%= label_tag :Position %><br/>
          <%= text_field_tag :position_text, @position_text %>
        </p>
        <p>
          <%= label_tag :Description %><br/>
          <%= text_field_tag :description_text, @description_text %>
        </p>
        <p>
          <%= label_tag :Pay %><br/>
          <%= select_tag :paid_text, options_for_select(@pay, @paid_text) %>
        </p>
        <p>
          <%= label_tag :Requirements %><br/>
          <%= text_field_tag :requirements_text, @requirements_text %>
        </p>
        <p>
          <%= label_tag :Culture %><br/>
          <%= select_tag :culture, options_for_select(@cultures, @culture) %>
        </p>
        <p>
          <%= submit_tag 'Search' %>
          <%= submit_tag 'Save Search', :name => 'save_search'%>
        </p>
    <% end %>
  </div>


  <div style="display:inline-block; width:75%;">
    <% if !@saved.empty? %>
        <h3>Saved Searches</h3>

        <table>
          <tr>
            <th>Position</th>
            <th>Description</th>
            <th>Pay</th>
            <th>Requirements</th>
            <th>Culture</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>

          <% @saved.each do |search| %>
              <tr>
                <td><%= search.position_text %></td>
                <td><%= search.description_text %></td>
                <td><%= search.paid_text %></td>
                <td><%= search.requirements_text %></td>
                <td><%= search.culture %></td>
                <td><%= link_to "Visit", search_job_postings_url(:position_text => search.position_text,
                                                                  :description_text => search.description_text,
                                                                  :paid_text => search.paid_text,
                                                                  :requirements_text => search.requirements_text,
                                                                  :culture => search.culture) %></td>
                <td><%= link_to "Edit", edit_saved_job_posting_url(search) %></td>
                <td><%= link_to 'Destroy', search, :method=>:delete, :confirm=>'Are you sure?' %></td>
              </tr>
          <% end %>
        </table>
    <% end %>
  </div>

</div><br />






<div>
  <% if !@return.nil? && !@return.empty? %>
      <h3>Search Results</h3>
      <table>
        <tr>
          <th>Company Profile</th>
          <th>Company Culture Grouping</th>

          <th>Position</th>
          <th>Job description</th>
          <th>Job start</th>
          <th>Job end</th>
          <th>Posted on</th>
          <th>Position time</th>
          <th>Job paid</th>
          <th>Job requirements</th>

        </tr>

        <% @return.each do |job_posting| %>
            <tr>
              <% com_prof = CompanyProfile.find(job_posting.company_profile_id) %>
              <td><%= link_to com_prof.company_name, company_profile_url(com_prof) %></td>
              <td><%= com_prof.qsort %></td>

              <td><%= job_posting.position %></td>
              <td><%= job_posting.job_description %></td>
              <td><%= job_posting.job_start %></td>
              <td><%= job_posting.job_end %></td>
              <td><%= job_posting.posted_on %></td>
              <td><%= job_posting.position_time %></td>
              <td><%= job_posting.job_paid %></td>
              <td><%= job_posting.job_requirements %></td>

            </tr>
        <% end %>
      </table>

      <br />
  <% else %>
      <h3>No results.</h3>
  <% end %>
</div>

app/views/job_postings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Job:</b>
  <%= @job_posting.job_id %>
</p>

<p>
  <b>Position:</b>
  <%= @job_posting.position %>
</p>

<p>
  <b>Job description:</b>
  <%= @job_posting.job_description %>
</p>

<p>
  <b>Job start:</b>
  <%= @job_posting.job_start %>
</p>

<p>
  <b>Job end:</b>
  <%= @job_posting.job_end %>
</p>

<p>
  <b>Posted on:</b>
  <%= @job_posting.posted_on %>
</p>

<p>
  <b>Position time:</b>
  <%= @job_posting.position_time %>
</p>

<p>
  <b>Job paid:</b>
  <%= @job_posting.job_paid %>
</p>

<p>
  <b>User:</b>
  <%= @job_posting.user_id %>
</p>

<p>
  <b>Job requirements:</b>
  <%= @job_posting.job_requirements %>
</p>

<p>
  <b>Company profile:</b>
  <%= @job_posting.company_profile_id %>
</p>


<%= link_to 'Edit', edit_job_posting_url(@job_posting) %> |
<%= link_to 'Back', job_postings_url %>