config/routes.rb
Intern::Application.routes.draw do
  resources :saved_student_profiles

  resources :saved_job_postings

  ActiveAdmin.routes(self)

  devise_for :users, :controllers => {:registrations => "registrations"}

  root :to => "student_profiles#index"

  resources :skills
  resources :stu_references
  resources :job_postings do
    collection do
      get 'search'
    end
  end
  resources :company_profiles
  resources :student_profiles do
  	  collection do
			get 'search'
	end
  end
  resources :stu_work_experiences

  resources :qsorts do
    post :sort, on: :collection
  end

  match "about" => "about#index"

end

app/models/qsort.rb
class Qsort < ActiveRecord::Base
  acts_as_list
  attr_accessible :name, :position

end

app/controllers/qsorts_controller.rb
class QsortsController < ApplicationController
  # GET /qsorts
  # GET /qsorts.json\
  before_filter :authenticate_user!, :get_user
  #keep user from accessing pages if they haven't created their profile yet
  before_filter :profile_redir


  def index
    #@qsorts = Qsort.all
    #@qsorts = Qsort.order('qsorts.position ASC')
    @id = current_user.id.to_s

    @lines = File.read('public/qsort.txt').split("\n")

    @h = Hash.new
    @lines.each do |line|
      s = line.split(' ', 2)
      @h[s[0]] = s[1]
    end

    if !@h[@id].nil?
      s = @h[@id].split()
      @qsorts = []
      s.each do |id|
        @qsorts.append(Qsort.find(id))
      end
    else
      @qsorts = Qsort.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @qsorts }
    end
  end

  def sort
    @id = current_user.id.to_s

    @qsorts = Qsort.all
    @qsorts.each do |qsort|
      qsort.position = params['qsort'].index(qsort.id.to_s)+1
      qsort.save
    end

    @lines = File.read('public/qsort.txt').split("\n")

    @h = Hash.new
    @lines.each do |line|
      s = line.split(' ', 2)
      @h[s[0]] = s[1]
    end

#h is filled with all ids as a key and related positions as a string

    @h[@id] = ''

    @items = Qsort.order('qsorts.position ASC')
    @items.each do |item|
      #@temp = item.id.to_s.concat(' ')
      @h[@id].concat(item.id.to_s.concat(' '))
    end


#store hash in s
    s = ''
    @h.each do |id,line|
      s.concat("#{id} #{line}\n")
    end

#write s to file
    File.write('public/qsort.txt', s)

=begin
    @items = Qsort.order('qsorts.position ASC')
    @items.each do |item|
      @lst.append(item.id)
    end
    f.puts(@lst.join(' '))
    f.close
=end

    render :nothing => true
  end



  # GET /qsorts/1
  # GET /qsorts/1.json
  def show
    @qsort = Qsort.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @qsort }
    end
  end

  # GET /qsorts/new
  # GET /qsorts/new.json
  def new
    @qsort = Qsort.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @qsort }
    end
  end

  # GET /qsorts/1/edit
  def edit
    @qsort = Qsort.find(params[:id])
  end

  # POST /qsorts
  # POST /qsorts.json
  def create
    @qsort = Qsort.new(params[:qsort])

    respond_to do |format|
      if @qsort.save
        format.html { redirect_to @qsort, notice: 'Qsort was successfully created.' }
        format.json { render json: @qsort, status: :created, location: @qsort }
      else
        format.html { render action: "new" }
        format.json { render json: @qsort.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /qsorts/1
  # PUT /qsorts/1.json
  def update
    @qsort = Qsort.find(params[:id])

    respond_to do |format|
      if @qsort.update_attributes(params[:qsort])
        format.html { redirect_to @qsort, notice: 'Qsort was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @qsort.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qsorts/1
  # DELETE /qsorts/1.json
  def destroy
    @qsort = Qsort.find(params[:id])
    @qsort.destroy

    respond_to do |format|
      format.html { redirect_to qsorts_url }
      format.json { head :no_content }
    end
  end
end

app/views/qsorts/_form.html.erb
<%= form_for(@qsort) do |f| %>
  <% if @qsort.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@qsort.errors.count, "error") %> prohibited this qsort from being saved:</h2>

      <ul>
      <% @qsort.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :position %><br />
    <%= f.number_field :position %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/qsorts/edit.html.erb
<h1>Editing qsort</h1>

<%= render 'form' %>

<%= link_to 'Show', @qsort %> |
<%= link_to 'Back', qsorts_url %>

app/views/qsorts/index.html.erb
<h1>Attitudinal Survey</h1>

    <p>Please sort the attributes from most like you to least like you.  Hit "Back" when you are through.</p>


    <ul id="qsorts"> <% @qsorts.each do |qsort| %>
        <li class="ui-state-default" id="qsort_<%= qsort.id %>"><span class="handle"><%= qsort.name %></span></li>
    <% end %></ul>




<br />

<%# link_to 'New Qsort', new_qsort_url %>
<%= link_to 'Back', @user %>

app/views/qsorts/new.html.erb
<h1>New qsort</h1>

<%= render 'form' %>

<%= link_to 'Back', qsorts_url %>

app/views/qsorts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @qsort.name %>
</p>

<p>
  <b>Position:</b>
  <%= @qsort.position %>
</p>


<%= link_to 'Edit', edit_qsort_url(@qsort) %> |
<%= link_to 'Back', qsorts_url %>